# Generated by Django 5.2.14 on 2026-09-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('kn', 'ಕನ್ನಡ'), ('hi', 'हिन्दी')], default='en', max_length=5),
        ),
    ]
