# Generated by Django 5.2.14 on 2026-09-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='government_request_status',
            field=models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('kn', 'Kannada'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
    ]
