# Generated by Django 5.2.14 on 2026-08-29 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_latitude_issue_longitude_alter_issue_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
