# Generated by Django 6.1.1 on 2026-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_issuestatushistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatushistory',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='old_status',
            field=models.CharField(max_length=30),
        ),
    ]
